version: '3'
services:
  semanticapi:
    container_name: "semanticapi"
    build: ./SemanticAPI/API
    ports: 
     - "8001:8000"
    restart: always
    environment:
      - ADMIN_PASSWORD=a8owisjdfooü
  semanticserver:
    image: stain/jena-fuseki
    container_name: "semanticserver"
    links:
      - semanticapi
    environment:
      - ADMIN_PASSWORD=a8owisjdfooü
    ports:
     - "3031:3030"
    restart: always
  webapp:
    container_name: "webapp"
    build: ./Webapp
    ports:
      - "8002:8000"
    restart: always