version: '3'
services:
  semanticapi:
    container_name: "semanticapi"
    build: ./SemanticAPI/API
    ports: 
     - "8021:8000"
    restart: always
  webapp:
    container_name: "webapp"
    build: ./WebApp
    ports:
      - "8022:8000"
    restart: always
    environment:
      - inDockerContainer=True
